[package]
name = "pretty"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "pretty"

[lib]
path = "src/lib.rs"


[dependencies]
clap = { version = "4.0.32", features = ["derive",] }
serde_json = { version = "1.0", features = ["preserve_order"] }
